# Omakase Ruby styling for Rails
#inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Metrics/MethodLength:
  CountAsOne: ['heredoc']

RSpecRails/InferredSpecType:
  Enabled: false

Style/Documentation:
  Enabled: false
