test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use bin/rails credentials:edit to set the S3 secrets (as regru:access_key_id|secret_access_key)
regru_cloud:
  service: S3
  endpoint: https://s3.regru.cloud
  access_key_id: <%= Rails.application.credentials.dig(:regru, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:regru, :secret_access_key) %>
  bucket: <%= Rails.env.production? ? 'siblings' : 'siblings-dev' %>

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# Use bin/rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
